In [271]:
%pylab inline
import re
import math
import string
from collections import Counter
from __future__ import division
import numpy as np
import pandas as pd

Populating the interactive namespace from numpy and matplotlib


/Users/uditagupta93/anaconda3/lib/python3.6/site-packages/IPython/core/magics/pylab.py:160: UserWarning: pylab import has clobbered these variables: ['delete']
`%matplotlib` prevents importing * from pylab and numpy
  "\n`%matplotlib` prevents importing * from pylab and numpy"


In [272]:
#we use re package to filter out unnecessary characters, tokenize the words and convert it to lower case
def tokens(text):
    return re.findall('[a-z]+', text.lower()) 

In [273]:
#we use re package to filter out unnecessary characters, tokenize the words and convert it to lower case
def tokens_words(text):
    x = re.findall('[a-z]+', text.lower()) 
    #print(x)
    return str(x[0])

In [274]:
TEXT = open('big.txt').read() #read all the words from big.txt
len(TEXT)

6488665

In [275]:
#spell_errors = open("spell-errors.txt").read()
#len(spell_errors)

In [283]:
delete = [':','?',';',',','>']

def load_spell_errors(filename, sep=':'):
    spell_errors_dict = {}
    """Return a Counter initialized from key-value pairs, 
    one on each line of filename."""
    for line in open(filename):
        x = line.split(sep)
        key = x[0]
        if key not in delete:
            key = tokens_words(key)
            val = x[1:]
            val = val[0].split(',')
            #print(val)
            for i in range(len(val)):

                val[i] = val[i].strip()
                val[i] = tokens_words(val[i])
                #print(i)


            spell_errors_dict[key]=val

    return spell_errors_dict


spell_errors_dict = load_spell_errors('spell-errors.txt')
print(len(spell_errors_dict))
#print(spell_errors_dict)

7506


In [232]:
# Empty matrix decleration



In [286]:
deletion_matrix = np.zeros((26,26), dtype=int)
insertion_matrix = np.zeros((26,26), dtype=int)
substitution_matrix = np.zeros((26,26), dtype=int)
transposition_matrix = np.zeros((26,26), dtype=int)

alphabets_dict = {'a':0,'b':1,'c':2,'d':3,'e':4,'f':5,'g':6,'h':7,
    'i':8,'j':9,'k':10,'l':11,'m':12,'n':13,'o':14,'p':15,'q':16,'r':17,
    's':18,'t':19,'u':20,'v':21,'w':22,'x':23,'y':24,'z':25
    }

# Populating matrices
#temp_dict = {'yellow': ['yellowa']}
q=0
for key, value in temp_dict.items():
    q+=1
    for val in value:
        #For insertion
        temp_val = val
        temp_key = key
        if len(val) > len(key):
            for char in temp_val:
                if char not in temp_key:
                    char1 = alphabets_dict[temp_val[temp_val.find(char)-1]]
                    char2 = alphabets_dict[char]
                    insertion_matrix[char1][char2] += 1
                    break
                else:
                    temp_key.replace(char, '')
        #For deletion
        elif len(val) < len(key):
            for char in temp_key:
                if char not in temp_val:
                    #print(q)
                    #print(temp_val,char,q,temp_key.find(char))
                    #print(alphabets_dict[temp_val[temp_key.find(char)-1]])
                    char1 = alphabets_dict[temp_key[temp_key.find(char)-1]]
                    char2 = alphabets_dict[char]
                    deletion_matrix[char1][char2] += 1
                    break
                else:
                    temp_val.replace(char, '')
                    
                    
        #For Substitution and transposition
        elif len(val) == len(key):
            for i in range(len(val)):
                if key[i] != val[i]:
                    if i == len(key)-1:
                        char1 = int(alphabets_dict[key[i]])
                        char2 = int(alphabets_dict[val[i]])                       
                        substitution_matrix[char1, char2] +=1
                        break
                    elif key[i+1] == val[i] and key[i] == val[i+1]:
                        char1 = int(alphabets_dict[key[i]])
                        char2 = int(alphabets_dict[key[i+1]])
                        transposition_matrix[char1][char2] +=1
                        break
        else:
            print(val,q)
                    
print(insertion_matrix)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 

In [159]:
tokens('This is: A test, 1, 2, 3, this is.')

['this', 'is', 'a', 'test', 'this', 'is']

In [160]:
WORDS = tokens(TEXT)
counts_sum = len(WORDS)

In [161]:
print(WORDS[:10]) #print first few words

['the', 'project', 'gutenberg', 'ebook', 'of', 'the', 'adventures', 'of', 'sherlock', 'holmes']


In [162]:
def sample(bag, n=10):
    return ' '.join(random.choice(bag) for _ in range(n))

In [163]:
sample(WORDS)

'with clad did cells rustle fellows he the neither and'

In [164]:
Counter(tokens('Is this a test? It is a test!')) #to make up something like a dictionary to store the number of occourences of every word

Counter({'a': 2, 'is': 2, 'it': 1, 'test': 2, 'this': 1})

In [165]:
COUNTS = Counter(WORDS)

print(COUNTS.most_common(10))

[('the', 80030), ('of', 40025), ('and', 38313), ('to', 28766), ('in', 22050), ('a', 21155), ('that', 12512), ('he', 12401), ('was', 11410), ('it', 10681)]


In [166]:
for w in tokens('the rare and neverbeforeseen words'):
    print(w,COUNTS[w])

the 80030
rare 83
and 38313
neverbeforeseen 0
words 460


In [168]:
def load_counts(filename, sep='\t'):
    """Return a Counter initialized from key-value pairs, 
    one on each line of filename."""
    C = Counter()
    for line in open(filename):
        key, count = line.split(sep)
        C[key] = int(count)
    return C


COUNTS1 = load_counts('count_1w.txt')


In [169]:
print(COUNTS1.most_common(10))


[('the', 23135851162), ('of', 13151942776), ('and', 12997637966), ('to', 12136980858), ('a', 9081174698), ('in', 8469404971), ('for', 5933321709), ('is', 4705743816), ('on', 3750423199), ('that', 3400031103)]


In [171]:
COUNTS1_dict = dict(COUNTS1)

In [172]:
# get the overall corpus count
counts1_sum = 0
for val in COUNTS1_dict.values():
    counts1_sum += val
    
print(counts1_sum)

588124220187


### Spell Checker
        


In [173]:
def correct(word):
    #Generating all the words with edit distance of 0, 1 & 2
    candidates = (known(edits0(word)) or 
                  known(edits1(word)) or 
                  known(edits2(word)) or 
                  [word])
    print(candidates)
    print(COUNTS.get)
    print(max(candidates, key=COUNTS.get))
    return(candidates)
    #return max(candidates, key=COUNTS.get)

In [174]:
def known(words):
    #Return the subset of words that are actually in the dictionary."
    return {w for w in words if w in COUNTS}

def edits0(word): 
    return {word}

def edits2(word):
    return {e2 for e1 in edits1(word) for e2 in edits1(e1)}

Now for `edits1(word)`: the set of candidate words that are one edit away. For example, given `"wird"`, this would include `"weird"` (inserting an `e`) and `"word"` (replacing a `i` with a `o`), and also `"iwrd"` (transposing `w` and `i`; then `known` can be used to filter this out of the set of final candidates). How could we get them?  One way is to *split* the original word in all possible places, each split forming a *pair* of words, `(a, b)`, before and after the place, and at each place, either delete, transpose, replace, or insert a letter:

<table>
  <tr><td> pairs: <td><tt> Ø+wird <td><tt> w+ird <td><tt> wi+rd <td><tt>wir+d<td><tt>wird+Ø<td><i>Notes:</i><tt> (<i>a</i>, <i>b</i>)</tt> pair</i>
  <tr><td> deletions: <td><tt>Ø+ird<td><tt> w+rd<td><tt> wi+d<td><tt> wir+Ø<td><td><i>Delete first char of b</i>
  <tr><td> transpositions: <td><tt>Ø+iwrd<td><tt> w+rid<td><tt> wi+dr</tt><td><td><td><i>Swap first two chars of b
  <tr><td> replacements: <td><tt>Ø+?ird<td><tt> w+?rd<td><tt> wi+?d<td><tt> wir+?</tt><td><td><i>Replace char at start of b
  <tr><td> insertions: <td><tt>Ø+?+wird<td><tt> w+?+ird<td><tt> wi+?+rd<td><tt> wir+?+d<td><tt> wird+?+Ø</tt><td><i>Insert char between a and b
</table>

In [175]:
def edits1(word):
    pairs      = splits(word)
    deletes    = [a+b[1:]           for (a, b) in pairs if b]
    transposes = [a+b[1]+b[0]+b[2:] for (a, b) in pairs if len(b) > 1]
    replaces   = [a+c+b[1:]         for (a, b) in pairs for c in alphabet if b]
    inserts    = [a+c+b             for (a, b) in pairs for c in alphabet]
    return set(deletes + transposes + replaces + inserts)

def splits(word):
    return [(word[:i], word[i:]) 
            for i in range(len(word)+1)]

alphabet = 'abcdefghijklmnopqrstuvwxyz'

In [176]:
splits('wird')

[('', 'wird'), ('w', 'ird'), ('wi', 'rd'), ('wir', 'd'), ('wird', '')]

In [177]:
print(edits0('wird'))

{'wird'}


In [178]:
print(edits1('wird'))

{'wiry', 'wfird', 'wpird', 'whird', 'wiird', 'hird', 'widd', 'wimrd', 'qwird', 'wirzd', 'wiwd', 'wgrd', 'wirz', 'ywird', 'iird', 'yird', 'xwird', 'wirx', 'wrird', 'wirpd', 'wnird', 'wirid', 'wire', 'wtrd', 'wuird', 'wcird', 'wirnd', 'awird', 'wirds', 'wimd', 'wtird', 'fwird', 'wmrd', 'wirdp', 'vwird', 'wdird', 'wiro', 'wjrd', 'wizrd', 'wirxd', 'wirm', 'sird', 'swird', 'wbird', 'wurd', 'uwird', 'wirwd', 'wirdc', 'pird', 'iwird', 'iwrd', 'wirde', 'wirod', 'wprd', 'wsird', 'wisd', 'wirr', 'owird', 'wxird', 'cwird', 'wcrd', 'pwird', 'waird', 'wind', 'wirt', 'wicrd', 'wirqd', 'wiard', 'wibrd', 'wyrd', 'hwird', 'wdrd', 'wiqd', 'uird', 'wifd', 'wrd', 'wiru', 'widrd', 'wirc', 'mird', 'wiad', 'rwird', 'wisrd', 'cird', 'wibd', 'wnrd', 'wipd', 'wirg', 'fird', 'wyird', 'wifrd', 'twird', 'wjird', 'wirdt', 'wwrd', 'wirn', 'wirdl', 'wqrd', 'wirdg', 'wzrd', 'wird', 'wvrd', 'wixd', 'kwird', 'wirgd', 'wxrd', 'wirdz', 'mwird', 'widr', 'wigd', 'wirp', 'wirh', 'wlird', 'wvird', 'wirdb', 'wirdu', 'wirfd', '

In [179]:
print(len(edits2('wird')))

24254


In [180]:
list(map(correct, tokens('acress')))

{'across', 'acres', 'caress', 'actress', 'access'}
<built-in method get of Counter object at 0x122155e08>
across


[{'access', 'acres', 'across', 'actress', 'caress'}]

In [181]:
probability_of_w = {}
candidate_list = list(map(correct, tokens('acress')))

for candidate in candidate_list[0]:
    if candidate in COUNTS1_dict:
        probability_of_w[candidate] = (COUNTS1_dict[candidate]/counts1_sum)
    else:
        probability_of_w[candidate] = (COUNTS[candidate]/counts_sum)
        
print(probability_of_w)

{'across', 'acres', 'caress', 'actress', 'access'}
<built-in method get of Counter object at 0x122155e08>
across
{'across': 0.0001302397493094999, 'acres': 2.4159700471920942e-05, 'caress': 1.0032693430180253e-06, 'actress': 1.1919345878615715e-05, 'access': 0.0003706478606351033}


Can we make the output prettier than that?

In [182]:
def correct_text(text):
    return re.sub('[a-zA-Z]+', correct_match, text)

def correct_match(match):
    word = match.group()
    return case_of(word)(correct(word.lower()))

def case_of(text):
    return (str.upper if text.isupper() else
            str.lower if text.islower() else
            str.title if text.istitle() else
            str)

In [183]:
correct_text('Speling Errurs IN somethink. Whutever; unusuel misteakes?')

{'spelling'}
<built-in method get of Counter object at 0x122155e08>
spelling


TypeError: descriptor 'title' requires a 'str' object but received a 'set'

In [ ]:
correct_text('Audiance sayzs: tumblr ...')

In [ ]:
def pdist(counter):
    "Make a probability distribution, given evidence from a Counter."
    N = sum(list(counter.values()))
    return lambda x: counter[x]/N

P = pdist(COUNTS)

In [ ]:
for w in tokens('"The" is most common word in English'):
    print(P(w), w)

In [ ]:
def Pwords(words):
    return product(P(w) for w in words)

def product(nums):
    result = 1
    for x in nums:
        result *= x
    return result

In [ ]:
tests = ['this is a test', 
         'this is a unusual test',
         'this is a neverbeforeseen test']

for test in tests:
    print(Pwords(tokens(test)), test)

References:

https://web.stanford.edu/class/cs276/pa/pa2.p

http://web.stanford.edu/~jurafsky/slp3/5.pdf

http://norvig.com/ngrams/spell-errors.txt

http://nbviewer.jupyter.org/url/norvig.com/ipython/How%20to%20Do%20Things%20with%20Words.ipynb

http://norvig.com/big.txt

http://norvig.com/ngrams/count_1w.txt

http://norvig.com/ngrams/